// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReliefProject.Models;

namespace ReliefProject.Migrations
{
    [DbContext(typeof(ReliefDbContext))]
    [Migration("20220401173909_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("ReliefProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Toiletries"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Food"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Furniture"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Toys"
                        });
                });

            modelBuilder.Entity("ReliefProject.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("DonationId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            DonationId = 1,
                            Discount = "Free",
                            Notes = "",
                            ProductionId = 1,
                            Quantity = 500,
                            TimeStamp = new DateTime(2022, 4, 1, 11, 39, 8, 496, DateTimeKind.Local).AddTicks(8850)
                        },
                        new
                        {
                            DonationId = 2,
                            Discount = "Free",
                            Notes = "",
                            ProductionId = 2,
                            Quantity = 1000,
                            TimeStamp = new DateTime(2022, 4, 1, 11, 39, 8, 505, DateTimeKind.Local).AddTicks(2880)
                        },
                        new
                        {
                            DonationId = 3,
                            Discount = "50% Off",
                            Notes = "",
                            ProductionId = 3,
                            Quantity = 4500,
                            TimeStamp = new DateTime(2022, 4, 1, 11, 39, 8, 505, DateTimeKind.Local).AddTicks(2940)
                        },
                        new
                        {
                            DonationId = 4,
                            Discount = "Free",
                            Notes = "Manufacturing Issues",
                            ProductionId = 3,
                            Quantity = 500,
                            TimeStamp = new DateTime(2022, 4, 1, 11, 39, 8, 505, DateTimeKind.Local).AddTicks(2940)
                        },
                        new
                        {
                            DonationId = 5,
                            Discount = "Free",
                            Notes = "",
                            ProductionId = 4,
                            Quantity = 1200,
                            TimeStamp = new DateTime(2022, 4, 1, 11, 39, 8, 505, DateTimeKind.Local).AddTicks(2950)
                        });
                });

            modelBuilder.Entity("ReliefProject.Models.Humanitarian", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrgAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgState")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgZip")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("OrgId");

                    b.ToTable("Humanitarians");

                    b.HasData(
                        new
                        {
                            OrgId = 1,
                            OrgAddress = "88 Hamilton Ave",
                            OrgCity = "Stamford",
                            OrgCountry = "United States of America",
                            OrgName = "AmeriCares",
                            OrgPhone = "203-658-9500",
                            OrgState = "CT",
                            OrgZip = "06902",
                            RequesterEmail = "requester@americares.org",
                            RequesterFirstName = "John",
                            RequesterLastName = "Adams",
                            RequesterPhone = "555-765-4321"
                        },
                        new
                        {
                            OrgId = 2,
                            OrgAddress = "430 17th Street NW",
                            OrgCity = "Washington DC",
                            OrgCountry = "United States of America",
                            OrgName = "Red Cross",
                            OrgPhone = "202-303-4498",
                            OrgState = "DC",
                            OrgZip = "20006",
                            RequesterEmail = "requester@redcross.org",
                            RequesterFirstName = "George",
                            RequesterLastName = "Washington",
                            RequesterPhone = "555-123-4567"
                        },
                        new
                        {
                            OrgId = 3,
                            OrgAddress = "78 rue de Lausanne Case Postale 116",
                            OrgCity = "Geneva",
                            OrgCountry = "Switzerland",
                            OrgName = "Doctors Without Borders",
                            OrgPhone = "212-763-5779",
                            OrgState = "CH",
                            OrgZip = "1211",
                            RequesterEmail = "requester@doctors.org",
                            RequesterFirstName = "James",
                            RequesterLastName = "Madison",
                            RequesterPhone = "555-666-7777"
                        });
                });

            modelBuilder.Entity("ReliefProject.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 3,
                            Notes = "",
                            ProductName = "Water Bottle",
                            Size = "1L"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Notes = "",
                            ProductName = "T-Shirt",
                            Size = "M"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 5,
                            Notes = "Women's Size",
                            ProductName = "Basketball",
                            Size = "29 in"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Notes = "",
                            ProductName = "Paper Towel",
                            Size = "11 in"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 4,
                            Notes = "Queen Size",
                            ProductName = "Mattress",
                            Size = "60X80 in"
                        });
                });

            modelBuilder.Entity("ReliefProject.Models.Production", b =>
                {
                    b.Property<int>("ProductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductionId");

                    b.ToTable("Productions");

                    b.HasData(
                        new
                        {
                            ProductionId = 1,
                            Notes = "40 Count",
                            ProductId = 1,
                            SupplierId = 4
                        },
                        new
                        {
                            ProductionId = 2,
                            Notes = "",
                            ProductId = 2,
                            SupplierId = 4
                        },
                        new
                        {
                            ProductionId = 3,
                            Notes = "12 Count",
                            ProductId = 4,
                            SupplierId = 4
                        },
                        new
                        {
                            ProductionId = 4,
                            Notes = "24 Count",
                            ProductId = 4,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductionId = 5,
                            Notes = "40 Count",
                            ProductId = 1,
                            SupplierId = 6
                        },
                        new
                        {
                            ProductionId = 6,
                            Notes = "",
                            ProductId = 3,
                            SupplierId = 6
                        },
                        new
                        {
                            ProductionId = 7,
                            Notes = "12 Count",
                            ProductId = 4,
                            SupplierId = 6
                        });
                });

            modelBuilder.Entity("ReliefProject.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AidType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HumanitarianId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            AidType = "Natural Disaster Recovery",
                            Amount = 1500,
                            HumanitarianId = 1,
                            Notes = "",
                            ProductId = 1,
                            TimeStamp = new DateTime(2022, 4, 1, 11, 39, 8, 506, DateTimeKind.Local).AddTicks(7640)
                        },
                        new
                        {
                            RequestId = 2,
                            AidType = "Third World Production",
                            Amount = 6000,
                            HumanitarianId = 3,
                            Notes = "",
                            ProductId = 4,
                            TimeStamp = new DateTime(2022, 4, 1, 11, 39, 8, 506, DateTimeKind.Local).AddTicks(8130)
                        },
                        new
                        {
                            RequestId = 3,
                            AidType = "Refugee Assistance",
                            Amount = 200,
                            HumanitarianId = 2,
                            Notes = "",
                            ProductId = 5,
                            TimeStamp = new DateTime(2022, 4, 1, 11, 39, 8, 506, DateTimeKind.Local).AddTicks(8150)
                        },
                        new
                        {
                            RequestId = 4,
                            AidType = "Refugee Assistance",
                            Amount = 2000,
                            HumanitarianId = 2,
                            Notes = "",
                            ProductId = 1,
                            TimeStamp = new DateTime(2022, 4, 1, 11, 39, 8, 506, DateTimeKind.Local).AddTicks(8160)
                        });
                });

            modelBuilder.Entity("ReliefProject.Models.Supplier", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrgAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgState")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgZip")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("OrgId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            OrgId = 4,
                            OrgAddress = "999 Lake Drive",
                            OrgCity = "Issaquah",
                            OrgCountry = "United States of America",
                            OrgName = "Kirkland",
                            OrgPhone = "425-313-8100",
                            OrgState = "WA",
                            OrgZip = "98027",
                            SupplierEmail = "supplier@kirkland.org",
                            SupplierFirstName = "James",
                            SupplierLastName = "Monroe",
                            SupplierPhone = "555-111-2222"
                        },
                        new
                        {
                            OrgId = 5,
                            OrgAddress = "1634 Beach Ave",
                            OrgCity = "Mehoopany",
                            OrgCountry = "United States of America",
                            OrgName = "Bounty",
                            OrgPhone = "570-833-5141",
                            OrgState = "PA",
                            OrgZip = "18629",
                            SupplierEmail = "supplier@bounty.org",
                            SupplierFirstName = "Alexander",
                            SupplierLastName = "Hamilton",
                            SupplierPhone = "555-333-4444"
                        },
                        new
                        {
                            OrgId = 6,
                            OrgAddress = "702 SW 8th St",
                            OrgCity = "St Bentonville",
                            OrgCountry = "United States of America",
                            OrgName = "Great Value",
                            OrgPhone = "801-221-0600",
                            OrgState = "AK",
                            OrgZip = "72716",
                            SupplierEmail = "supplier@walmart.org",
                            SupplierFirstName = "Benjamin",
                            SupplierLastName = "Franklin",
                            SupplierPhone = "555-888-9999"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
